# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField(default='')),
                ('picture', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
