# Generated by Django 2.0.3 on 2018-03-10 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restos.Customer')),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restos.Resto')),
            ],
        ),
    ]
