# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resto',
            old_name='code',
            new_name='description',
        ),
    ]
