# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restos', '0002_auto_20180216_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resto',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restos', to=settings.AUTH_USER_MODEL),
        ),
    ]
